// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB10SgzkVq5Sw89Oya86URwz1LyNN3jvUM',
    appId: '1:1018079275775:web:10dd6d5361fbafe66c7aca',
    messagingSenderId: '1018079275775',
    projectId: 'recipeapp-fc91c',
    authDomain: 'recipeapp-fc91c.firebaseapp.com',
    storageBucket: 'recipeapp-fc91c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJG1f7q0jmYkOSwyANynBNOM5D3WAQuGI',
    appId: '1:1018079275775:android:453b596e68711e326c7aca',
    messagingSenderId: '1018079275775',
    projectId: 'recipeapp-fc91c',
    storageBucket: 'recipeapp-fc91c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwXhkpSAITd-fO2-DhNIsgAwK_Y3y3ss0',
    appId: '1:1018079275775:ios:30f7168b4ae066f46c7aca',
    messagingSenderId: '1018079275775',
    projectId: 'recipeapp-fc91c',
    storageBucket: 'recipeapp-fc91c.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwXhkpSAITd-fO2-DhNIsgAwK_Y3y3ss0',
    appId: '1:1018079275775:ios:30f7168b4ae066f46c7aca',
    messagingSenderId: '1018079275775',
    projectId: 'recipeapp-fc91c',
    storageBucket: 'recipeapp-fc91c.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB10SgzkVq5Sw89Oya86URwz1LyNN3jvUM',
    appId: '1:1018079275775:web:01f601b04d1220ef6c7aca',
    messagingSenderId: '1018079275775',
    projectId: 'recipeapp-fc91c',
    authDomain: 'recipeapp-fc91c.firebaseapp.com',
    storageBucket: 'recipeapp-fc91c.firebasestorage.app',
  );
}
